### PR TITLE
Setup build logic

### PR DESCRIPTION
**Pull request by kibettheophilus**
---
name: Pull request
about: Create a pull request
label: 'triage me'
Fixes [Referenced Issue #](https://github.com/droidconKE/chai/issues).

---

---

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Ensure your branch is up to date with develop branch.
- [ ] Ensure your branch runs without breaking.
- [ ] Ensure you solved any merge conflicts.
- [ ] Smaller PRs for the ease of reviewing
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code! This means that we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass (`./gradlew --init-script gradle/init.gradle.kts spotlessApply` to automatically apply formatting)
- [ ] Appropriate docs were updated (You are adding code so...)
- [ ] Tests have been written

Is this your first Pull Request?
- [ ] Run `./tools/setup.sh`
- [ ] Import the code formatting style as explained in [the setup script](/tools/setup.sh#L40).

Fixes #<issue_number_goes_here> 🦕

# Screenshot
N/A

### CODE REVIEW

**Comment by tamzi** [comment]
@kibettheophilus still updating this?

**Comment by kibettheophilus** [comment]
> @kibettheophilus still updating this?



> @kibettheophilus still updating this?

Yes, I had forgotten about it...will finish it

**Comment by tamzi** [comment]
worth revisiting @kibettheophilus :)

**Comment by kibettheophilus** [comment]
@tamzi do we still really need to setup up this, because we have only 3 modules. 

thoughts @MamboBryan ?

**Comment by MamboBryan** [comment]
> @tamzi do we still really need to setup up this, because we have only 3 modules.
> 
> thoughts @MamboBryan ?

I think we don't really need it and can close it for now...

**Pull request closed without merging**
