### PR TITLE
drop dckeswag

### LINKED ISSUE #7: [FR]: have dckeswag as a separate app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

instead of minimizing importance of the dckeswag app separate it and run it as a separate app

### Describe the solution

Remove dckeswag and have it as a separate app :)

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tamzi**
---
name: Pull request
about: Create a pull request
label: 'triage me'
Fixes [Referenced Issue #](https://github.com/droidconKE/chai/issues)_.

---
## How can this PR be tested?
Run the branch. dckeswag will not be present. 
dckeswag has been moved to [dckeswag project](https://github.com/droidconKE/dckeswag)

---

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Ensure your branch is up to date with develop branch.
- [x] Ensure your branch runs without breaking.
- [x] Ensure you solved any merge conflicts.
- [x] Smaller PRs for the ease of reviewing
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code! This means that we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass (`./gradlew --init-script gradle/init.gradle.kts spotlessApply` to automatically apply formatting)
- [x] Appropriate docs were updated (You are adding code so...)
- [x] Tests have been written

Is this your first Pull Request?
- [ ] Run `./tools/setup.sh`
- [ ] Import the code formatting style as explained in [the setup script](/tools/setup.sh#L40).

Fixes #7 🦕

### CODE REVIEW

**Comment by tamzi** [comment]
@hopeman15 :)

**Review by hopeman15 — APPROVED** [review]
🧹

**Comment by tamzi** [comment]
merge this?

**Comment by tamzi** [comment]
merging this @wangerekaharun @hopeman15

**Pull request merged**
